//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollageDevices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string InventNumber { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Cabinet { get; set; }
        public string Comment { get; set; }
    }
}
